//! Key wrapping module for KESTREL Vault.
//!
//! Implements the Key Encryption Key (KEK) / Data Encryption Key (DEK)
//! hierarchy pattern. This is the industry-standard approach used by
//! AWS KMS, Google Cloud KMS, and Azure Key Vault.
//!
//! # Architecture
//!
//! ```text
//! Master Password
//!       │
//!       ▼
//! ┌──────────────┐
//! │  Argon2id    │  Key Derivation Function
//! │  (KEK)       │  Key Encryption Key
//! └──────┬───────┘
//!        │
//!        ▼ wrap/unwrap
//! ┌──────────────┐
//! │  DEK         │  Data Encryption Key (randomly generated)
//! │  (wrapped)   │  Stored encrypted in vault_meta
//! └──────┬───────┘
//!        │
//!        ▼ encrypt/decrypt fields
//! ┌──────────────┐
//! │  Vault Data  │  Passwords, notes, TOTP secrets, etc.
//! └──────────────┘
//! ```
//!
//! # Why KEK/DEK?
//!
//! 1. **Fast key rotation**: When the user changes their master password,
//!    only the DEK needs to be re-wrapped (encrypted with the new KEK).
//!    All vault data remains encrypted with the same DEK — no need to
//!    re-encrypt every field.
//!
//! 2. **Key separation**: The KEK (derived from password) is never used
//!    for bulk data encryption. The DEK (random) is never exposed outside
//!    of memory. This follows the cryptographic principle of key separation.
//!
//! 3. **Forward compatibility**: The DEK can be shared with multiple KEKs
//!    (e.g., for multi-user access or hardware key backup) without
//!    re-encrypting data.
//!
//! # Security
//!
//! - The DEK is a 256-bit random key generated by `OsRng`
//! - The DEK is wrapped (encrypted) with AES-256-GCM using the KEK
//! - The wrapped DEK includes AAD context to prevent swap attacks
//! - The unwrapped DEK is held in a `WrappedKey` struct that zeroizes on drop
//! - The KEK is the Argon2id-derived master key (already zeroized on drop)

use crate::crypto::envelope::{self, AadContext, EncryptedEnvelope};
use crate::crypto::kdf::DerivedKey;
use crate::crypto::random::random_bytes;
use crate::error::{KestrelError, KestrelResult};
use secrecy::{ExposeSecret, SecretBox};
use zeroize::ZeroizeOnDrop;

/// Length of the Data Encryption Key (DEK) in bytes.
/// 32 bytes = 256 bits for AES-256.
pub const DEK_LEN: usize = 32;

/// AAD context identifier for key wrapping operations.
/// This binds the wrapped DEK to the vault metadata entity,
/// preventing the wrapped key from being swapped with data
/// from a different context.
const KEYWRAP_AAD_ENTITY: &str = "vault_meta";
const KEYWRAP_AAD_FIELD: &str = "wrapped_dek";

/// A randomly generated Data Encryption Key (DEK).
///
/// This key is used for all field-level encryption/decryption
/// in the vault. It is generated once during vault initialization
/// and stored wrapped (encrypted) by the KEK.
///
/// # Security
///
/// - Generated using `OsRng` (cryptographically secure)
/// - Wrapped in `secrecy::Secret` — no Debug, no Clone of inner data
/// - Implements `ZeroizeOnDrop` — key material erased on drop
/// - Never persisted directly — only stored in wrapped (encrypted) form
#[derive(ZeroizeOnDrop)]
pub struct DataEncryptionKey {
    /// The raw DEK bytes, protected by secrecy and zeroize.
    key: SecretBox<[u8; DEK_LEN]>,
}

impl DataEncryptionKey {
    /// Generates a new random DEK using the operating system's CSPRNG.
    ///
    /// # Errors
    ///
    /// Returns `KestrelError::Crypto` if the system RNG fails.
    pub fn generate() -> KestrelResult<Self> {
        let mut key_bytes = [0u8; DEK_LEN];
        random_bytes(&mut key_bytes)?;
        Ok(DataEncryptionKey {
            key: SecretBox::new(Box::new(key_bytes)),
        })
    }

    /// Creates a DEK from raw key bytes.
    ///
    /// # Security
    ///
    /// The caller must ensure the input bytes are a legitimate
    /// cryptographic key, not arbitrary data.
    pub fn from_bytes(bytes: [u8; DEK_LEN]) -> Self {
        DataEncryptionKey {
            key: SecretBox::new(Box::new(bytes)),
        }
    }

    /// Exposes the raw DEK bytes for use in cryptographic operations.
    ///
    /// # Security
    ///
    /// The exposed reference should be used only for passing to
    /// encrypt/decrypt functions and must not be stored or logged.
    pub fn expose(&self) -> &[u8; DEK_LEN] {
        self.key.expose_secret()
    }

    /// Returns a reference to the DEK as a `DerivedKey`-like type
    /// for use with the cipher and envelope modules.
    ///
    /// # Security
    ///
    /// This creates a temporary `DerivedKey` that holds a copy of
    /// the DEK bytes. The `DerivedKey` is zeroized when dropped.
    pub fn as_derived_key(&self) -> DerivedKey {
        DerivedKey::new(*self.key.expose_secret())
    }
}

impl Clone for DataEncryptionKey {
    /// Clones the DEK by cloning the inner key bytes.
    ///
    /// # Security
    ///
    /// Each clone holds its own copy of the key material, which will
    /// be independently zeroized on drop. Minimize clones to reduce
    /// the attack surface for memory extraction.
    fn clone(&self) -> Self {
        DataEncryptionKey {
            key: SecretBox::new(Box::new(*self.key.expose_secret())),
        }
    }
}

/// The wrapped (encrypted) form of the Data Encryption Key.
///
/// This struct contains the DEK encrypted with the KEK (Key Encryption Key),
/// stored in the standard envelope format. It is persisted in the `vault_meta`
/// table alongside the salt and KDF parameters.
///
/// # Serialization
///
/// The wrapped DEK is serialized using the standard `EncryptedEnvelope`
/// binary format:
/// ```text
/// [version:1][nonce:12][ciphertext:N][tag:16]
/// ```
///
/// # Security
///
/// - The wrapped DEK cannot be used without the correct KEK
/// - The AAD context prevents swap attacks on the wrapped key
/// - The DEK plaintext is never stored — only the wrapped form is persisted
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct WrappedDek {
    /// The serialized envelope bytes for database storage.
    pub envelope_bytes: Vec<u8>,
}

impl WrappedDek {
    /// Creates a `WrappedDek` from raw envelope bytes.
    ///
    /// This is used when loading the wrapped DEK from the database.
    pub fn from_bytes(bytes: Vec<u8>) -> Self {
        WrappedDek { envelope_bytes: bytes }
    }

    /// Returns the envelope bytes for database storage.
    pub fn as_bytes(&self) -> &[u8] {
        &self.envelope_bytes
    }
}

/// Wraps (encrypts) the DEK with the KEK.
///
/// This function encrypts the Data Encryption Key using the Key Encryption
/// Key (the Argon2id-derived master key). The wrapped DEK is stored in
/// the vault metadata table.
///
/// # Arguments
///
/// * `kek` - The Key Encryption Key (derived from the master password)
/// * `dek` - The Data Encryption Key to wrap
///
/// # Returns
///
/// A `WrappedDek` containing the encrypted DEK in envelope format.
///
/// # Errors
///
/// Returns `KestrelError::Crypto` if encryption fails.
///
/// # Security
///
/// - Uses AES-256-GCM for authenticated encryption
/// - AAD context binds the wrapped DEK to the vault metadata entity
/// - Fresh nonce is generated for each wrap operation
/// - The DEK plaintext is never stored — only the wrapped form
pub fn wrap_dek(
    kek: &DerivedKey,
    dek: &DataEncryptionKey,
) -> KestrelResult<WrappedDek> {
    let envelope = envelope::seal_envelope(
        kek,
        dek.expose(),
        KEYWRAP_AAD_ENTITY,
        KEYWRAP_AAD_FIELD,
    )?;

    Ok(WrappedDek {
        envelope_bytes: envelope.to_bytes(),
    })
}

/// Unwraps (decrypts) the DEK with the KEK.
///
/// This function decrypts the wrapped Data Encryption Key using the
/// Key Encryption Key. This is the primary operation during vault unlock:
/// derive the KEK from the password, unwrap the DEK, then use the DEK
/// for field-level encryption.
///
/// # Arguments
///
/// * `kek` - The Key Encryption Key (derived from the master password)
/// * `wrapped_dek` - The wrapped DEK loaded from the database
///
/// # Returns
///
/// The unwrapped `DataEncryptionKey` on success.
///
/// # Errors
///
/// Returns `KestrelError::Crypto` if:
/// - The KEK is incorrect (wrong master password)
/// - The wrapped DEK has been tampered with
/// - The AAD context does not match
/// - The unwrapped key is not exactly 32 bytes
///
/// # Security
///
/// - GCM authentication verifies integrity before releasing the key
/// - The DEK is wrapped in `secrecy::Secret` and zeroized on drop
/// - A wrong KEK causes GCM authentication failure — the DEK is never
///   released with incorrect data
pub fn unwrap_dek(
    kek: &DerivedKey,
    wrapped_dek: &WrappedDek,
) -> KestrelResult<DataEncryptionKey> {
    let aad_context = AadContext::new(KEYWRAP_AAD_ENTITY, KEYWRAP_AAD_FIELD);
    let envelope = EncryptedEnvelope::from_bytes(&wrapped_dek.envelope_bytes, aad_context)?;

    let dek_bytes = envelope::open_envelope(kek, &envelope)?;

    if dek_bytes.len() != DEK_LEN {
        return Err(KestrelError::Crypto(format!(
            "Invalid DEK length: expected {} bytes, got {}",
            DEK_LEN,
            dek_bytes.len()
        )));
    }

    let mut key_array = [0u8; DEK_LEN];
    key_array.copy_from_slice(&dek_bytes);

    Ok(DataEncryptionKey::from_bytes(key_array))
}

/// Re-wraps the DEK with a new KEK.
///
/// This is the core operation for key rotation (password change).
/// Instead of re-encrypting all vault data with a new key, we only
/// re-encrypt (re-wrap) the DEK with the new KEK.
///
/// # Arguments
///
/// * `old_kek` - The current KEK (derived from the old password)
/// * `new_kek` - The new KEK (derived from the new password)
/// * `wrapped_dek` - The current wrapped DEK
///
/// # Returns
///
/// A new `WrappedDek` encrypted with the new KEK. The DEK itself
/// has NOT changed — only the wrapping has.
///
/// # Errors
///
/// Returns `KestrelError::Crypto` if the old KEK cannot unwrap the DEK.
///
/// # Security
///
/// - The DEK is only briefly in plaintext during the re-wrap
/// - The DEK is zeroized when it goes out of scope
/// - The old and new KEKs are never mixed
/// - This is O(1) — constant time regardless of vault size
pub fn rewrap_dek(
    old_kek: &DerivedKey,
    new_kek: &DerivedKey,
    wrapped_dek: &WrappedDek,
) -> KestrelResult<WrappedDek> {
    // Unwrap with old KEK
    let dek = unwrap_dek(old_kek, wrapped_dek)?;

    // Re-wrap with new KEK
    let new_wrapped = wrap_dek(new_kek, &dek)?;

    // dek is zeroized here when it goes out of scope
    Ok(new_wrapped)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::crypto::kdf::{derive_key, Salt};

    /// Helper: creates a test KEK.
    fn test_kek() -> DerivedKey {
        let salt = Salt([0x42u8; 16]);
        derive_key(b"test-kek-password", &salt).unwrap()
    }

    /// Helper: creates a different KEK (simulating a different password).
    fn test_kek_alt() -> DerivedKey {
        let salt = Salt([0x99u8; 16]);
        derive_key(b"test-kek-password-alt", &salt).unwrap()
    }

    #[test]
    fn dek_generation_is_random() -> KestrelResult<()> {
        let dek1 = DataEncryptionKey::generate()?;
        let dek2 = DataEncryptionKey::generate()?;
        assert_ne!(dek1.expose(), dek2.expose());
        Ok(())
    }

    #[test]
    fn dek_has_correct_length() -> KestrelResult<()> {
        let dek = DataEncryptionKey::generate()?;
        assert_eq!(dek.expose().len(), DEK_LEN);
        Ok(())
    }

    #[test]
    fn dek_from_bytes_preserves_data() {
        let bytes = [0xABu8; DEK_LEN];
        let dek = DataEncryptionKey::from_bytes(bytes);
        assert_eq!(dek.expose(), &bytes);
    }

    #[test]
    fn dek_clone_produces_same_key() -> KestrelResult<()> {
        let dek = DataEncryptionKey::generate()?;
        let cloned = dek.clone();
        assert_eq!(dek.expose(), cloned.expose());
        Ok(())
    }

    #[test]
    fn dek_as_derived_key_works() -> KestrelResult<()> {
        let dek = DataEncryptionKey::generate()?;
        let derived = dek.as_derived_key();
        assert_eq!(dek.expose(), derived.expose());
        Ok(())
    }

    #[test]
    fn wrap_unwrap_roundtrip() -> KestrelResult<()> {
        let kek = test_kek();
        let dek = DataEncryptionKey::generate()?;

        let wrapped = wrap_dek(&kek, &dek)?;
        let unwrapped = unwrap_dek(&kek, &wrapped)?;

        assert_eq!(dek.expose(), unwrapped.expose());
        Ok(())
    }

    #[test]
    fn wrap_produces_valid_envelope() -> KestrelResult<()> {
        let kek = test_kek();
        let dek = DataEncryptionKey::generate()?;
        let wrapped = wrap_dek(&kek, &dek)?;

        // Minimum envelope size: version(1) + nonce(12) + DEK(32) + tag(16) = 61
        assert!(wrapped.envelope_bytes.len() >= 61);
        // First byte should be version 1
        assert_eq!(wrapped.envelope_bytes[0], 0x01);
        Ok(())
    }

    #[test]
    fn wrong_kek_fails_unwrap() -> KestrelResult<()> {
        let kek = test_kek();
        let kek_alt = test_kek_alt();
        let dek = DataEncryptionKey::generate()?;

        let wrapped = wrap_dek(&kek, &dek)?;
        let result = unwrap_dek(&kek_alt, &wrapped);

        assert!(result.is_err());
        Ok(())
    }

    #[test]
    fn tampered_wrapped_dek_fails_unwrap() -> KestrelResult<()> {
        let kek = test_kek();
        let dek = DataEncryptionKey::generate()?;
        let wrapped = wrap_dek(&kek, &dek)?;

        let mut tampered_bytes = wrapped.envelope_bytes.clone();
        // Tamper with the last byte (part of the GCM tag or ciphertext)
        let last_idx = tampered_bytes.len() - 1;
        tampered_bytes[last_idx] ^= 0xFF;

        let tampered = WrappedDek::from_bytes(tampered_bytes);
        let result = unwrap_dek(&kek, &tampered);

        assert!(result.is_err());
        Ok(())
    }

    #[test]
    fn rewrap_dek_roundtrip() -> KestrelResult<()> {
        let old_kek = test_kek();
        let new_kek = test_kek_alt();
        let dek = DataEncryptionKey::generate()?;

        // Wrap with old KEK
        let wrapped_old = wrap_dek(&old_kek, &dek)?;

        // Re-wrap with new KEK
        let wrapped_new = rewrap_dek(&old_kek, &new_kek, &wrapped_old)?;

        // Unwrap with new KEK should give us the same DEK
        let unwrapped = unwrap_dek(&new_kek, &wrapped_new)?;
        assert_eq!(dek.expose(), unwrapped.expose());

        // Old KEK can no longer unwrap the new wrapped DEK
        let old_unwrap_result = unwrap_dek(&old_kek, &wrapped_new);
        assert!(old_unwrap_result.is_err());

        Ok(())
    }

    #[test]
    fn rewrap_preserves_dek_unchanged() -> KestrelResult<()> {
        let old_kek = test_kek();
        let new_kek = test_kek_alt();
        let dek = DataEncryptionKey::generate()?;

        let wrapped_old = wrap_dek(&old_kek, &dek)?;
        let wrapped_new = rewrap_dek(&old_kek, &new_kek, &wrapped_old)?;

        // Both old and new wrapped DEKs should decrypt to the same DEK
        let dek_from_old = unwrap_dek(&old_kek, &wrapped_old)?;
        let dek_from_new = unwrap_dek(&new_kek, &wrapped_new)?;

        assert_eq!(dek_from_old.expose(), dek_from_new.expose());
        Ok(())
    }

    #[test]
    fn wrapped_dek_from_bytes_roundtrip() -> KestrelResult<()> {
        let kek = test_kek();
        let dek = DataEncryptionKey::generate()?;
        let wrapped = wrap_dek(&kek, &dek)?;

        // Serialize and deserialize
        let bytes = wrapped.envelope_bytes.clone();
        let restored = WrappedDek::from_bytes(bytes);
        assert_eq!(wrapped.as_bytes(), restored.as_bytes());

        // Should still unwrap correctly
        let unwrapped = unwrap_dek(&kek, &restored)?;
        assert_eq!(dek.expose(), unwrapped.expose());
        Ok(())
    }

    #[test]
    fn dek_zeroizes_on_drop() -> KestrelResult<()> {
        let dek = DataEncryptionKey::generate()?;
        // We can't directly verify zeroization after drop,
        // but the ZeroizeOnDrop impl should run without panicking.
        drop(dek);
        Ok(())
    }

    #[test]
    fn too_short_wrapped_dek_fails() {
        let kek = test_kek();
        let wrapped = WrappedDek::from_bytes(vec![0x01, 0x02, 0x03]);
        let result = unwrap_dek(&kek, &wrapped);
        assert!(result.is_err());
    }

    #[test]
    fn invalid_version_in_wrapped_dek_fails() -> KestrelResult<()> {
        let kek = test_kek();
        let dek = DataEncryptionKey::generate()?;
        let wrapped = wrap_dek(&kek, &dek)?;

        let mut bad_bytes = wrapped.envelope_bytes.clone();
        bad_bytes[0] = 0xFF; // Invalid version

        let bad_wrapped = WrappedDek::from_bytes(bad_bytes);
        let result = unwrap_dek(&kek, &bad_wrapped);
        assert!(result.is_err());
        Ok(())
    }
}
